apiVersion: v1
kind: Pod
metadata:
  name: publisher
  namespace: zerotesting
spec:
  restartPolicy: Never
  dnsConfig:
    searches:
      - zerotesting-service.zerotesting.svc.cluster.local
  containers:
    - name: publisher-container
      image: soutullostatus/publisher:testing
      imagePullPolicy: Always
      command:
        - sh
        - -c
        - |
          python /app/traffic.py \
          --messages=300 \
          --msg-size-kbytes=1 \
          --delay-seconds=1 \
          --pubsub-topic="/waku/2/rs/2/" \
          --protocols relay 
