apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nomos-prof-ibd
  namespace: nomos-testnet
spec:
  serviceName: nomos-service
  replicas: 1

  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain

  selector:
    matchLabels:
      app: nomos
      pool: p-ibd

  template:
    metadata:
      labels:
        app: nomos
        pool: p-ibd
    spec:
      terminationGracePeriodSeconds: 300

      nodeSelector:
        kubernetes.io/hostname: node-04.ih-eu-mda1.misc.vaclab

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: nomos

      containers:
        - name: nomos
          image: soutullostatus/blockchain-mem-fix-profilig:ccae6b59
          imagePullPolicy: Always

          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    echo "preStop: sending SIGINT to PID 1"
                    kill -2 1
                    sleep 20

          resources:
            requests:
              memory: "1024Mi"
              cpu: "1000m"
            limits:
              memory: "4096Mi"
              cpu: "2000m"

          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

          volumeMounts:
            - name: nomos-data
              mountPath: /data

          command: ["/bin/sh", "-c"]
          args:
            - |
              set -eu

              cd /data

              ORD="${HOSTNAME##*-}"
              BASE=31100
              SWARM=$((BASE + 2*ORD))
              BLEND=$((SWARM + 1))

              if [ ! -f user_config.yaml ]; then
                logos-blockchain-node init \
                  --net-port "${SWARM}" \
                  --blend-port "${BLEND}" \
                  --external-address "/ip4/${HOST_IP}/udp/${SWARM}/quic-v1" \
                  -p /ip4/65.109.51.37/udp/3000/quic-v1/p2p/12D3KooWL7a8LBbLRYnabptHPFBCmAs49Y7cVMqvzuSdd43tAJk8 \
                  -p /ip4/65.109.51.37/udp/3001/quic-v1/p2p/12D3KooWPLeAcachoUm68NXGD7tmNziZkVeMmeBS5NofyukuMRJh \
                  -p /ip4/65.109.51.37/udp/3002/quic-v1/p2p/12D3KooWKFNe4gS5DcCcRUVGdMjZp3fUWu6q6gG5R846Ui1pccHD \
                  -p /ip4/65.109.51.37/udp/3003/quic-v1/p2p/12D3KooWAnriLgXyQnGTYz1zPWPkQL3rthTKYLzuAP7MMnbgsxzR
              fi

              sed -i '/^  metrics: None$/c\
                metrics: !Otlp\
                  endpoint: "http://otel-opentelemetry-collector.opentelemetry:4317/"\
                  host_identifier: "'"${HOSTNAME}"'"' user_config.yaml

              sed -i '/^    file:/,/^    loki:/{
              /^    file:/c\
                  file: null
              /^      directory:/d
              /^      prefix:/d
              }' user_config.yaml

              exec logos-blockchain-node user_config.yaml

  volumeClaimTemplates:
    - metadata:
        name: nomos-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn-nomos
        resources:
          requests:
            storage: 20Gi