apiVersion: v1
kind: Pod
metadata:
  name: publisher
  namespace: zerotesting
spec:
  restartPolicy: Never
  dnsConfig:
    searches:
      - zerotesting-service.zerotesting.svc.cluster.local
  containers:
    - name: publisher-container
      image: soutullostatus/publisher:v0.4.0
      imagePullPolicy: Always
      command:
        - sh
        - -c
        - python /app/traffic.py --messages=480  --msg-size-kbytes=1 --delay-seconds=5 --pubsub-topic="/waku/2/rs/2/0" --debug
