apiVersion: v1
kind: Service
metadata:
  name: zerotesting-store
  namespace: zerotesting
spec:
  clusterIP: None
  selector:
    app: zerotenkay-store
  ports:
  - protocol: TCP
    port: 8645
    targetPort: 8645
