apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pod
  namespace: zerotesting-pwhite
spec:
  replicas: 30
  podManagementPolicy: "Parallel"
  serviceName: nimp2p-service
  selector:
    matchLabels:
      app: zerotenkay
  template:
    metadata:
      labels:
        app: zerotenkay
    spec:
      dnsConfig:
        searches:
          - nimp2p-service.zerotesting-pwhite.svc.cluster.local
      containers:
        - name: container-0
          # image: soutullostatus/dst-test-node:v1.14.0-yamux
          # image: ufarooqstatus/refactored-test-node:v1.0
          image: pearsonwhite/test_node:c16faa8fb1d18570823e3a511e8a91618e13d937
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
            - containerPort: 8008
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "600Mi"
              cpu: "400m"
          env:
            # # - name: PEERNUMBER
            # #   value: "0"
            # - name: PEERS
            #   value: "12"
            # - name: CONNECTTO
            #   value: "10"
            # - name: MUXER
            #   value: yamux
            # # - name: MSGRATE
            # #   value: "10000"
            # # - name: MSGSIZE
            # #   value: "1000"

            - name: "NODES"
              value: "12"
            - name: "MESSAGES"
              value: "1000"
            - name: "MSGRATE"
              value: "1000"
            - name: "MSGSIZE"
              value: "1000"
            - name: "PUBLISHERS"
              value: "6"
            - name: "ISMIX"
              value: "false"
            - name: "CONNECTTO"
              value: "6"
            - name: "NUMMIX"
              value: "0"
            - name: "SELFTRIGGER"
              value: "false"


          args:
            - "55"
            - "20"
