version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s'
handlers:
  console_handler:
    level: "INFO"
    formatter: "simple"
    class: "logging.StreamHandler"
    stream: "ext://sys.stdout"
loggers:
  src:
    level: "INFO"
    handlers:
      - "console_handler"
    propagate: True