blend:
  common:
    num_blend_layers: 1
    minimum_network_size: 1
    protocol_name: /logos-blockchain-devnet/blend/1.0.0
    data_replication_factor: 0
  core:
    scheduler:
      cover:
        message_frequency_per_round: 1.0
        intervals_for_safety_buffer: 100
      delayer:
        maximum_release_delay_in_rounds: 1
    minimum_messages_coefficient: 1
    normalization_constant: 1.03
    activity_threshold_sensitivity: 1
network:
  kademlia_protocol_name: /logos-blockchain-devnet/kad/1.0.0
  identify_protocol_name: /logos-blockchain-devnet/identify/1.0.0
  chain_sync_protocol_name: /logos-blockchain-devnet/chainsync/1.0.0
cryptarchia:
  epoch_config:
    epoch_stake_distribution_stabilization: 3
    epoch_period_nonce_buffer: 3
    epoch_period_nonce_stabilization: 4
  security_param: 30
  slot_activation_coeff:
    numerator: 1
    denominator: 20
  learning_rate: 0.5
  sdp_config:
    service_params:
      BN:
        lock_period: 10
        inactivity_period: 1
        retention_period: 1
        timestamp: 0
    min_stake:
      threshold: 1
      timestamp: 0
  gossipsub_protocol: /logos-blockchain-devnet/cryptarchia/1.0.0
  genesis_state:
    mantle_tx:
      ops:
      - opcode: 0
        payload:
          inputs: []
          outputs:
          - value: 100000
            pk: 8bcf3c26847ab7c8d3277d2fac560956334540055d63bcbe4b91ffbd9d6e8419
          - value: 1
            pk: 7f0ed214dc9e501943b4060a0b34ec7daa6a26198611e5e75b175781e3be1922
          - value: 100
            pk: 6e1f152db9ec631fdc820f48062e87fa05a1bf1a114b2ce0f6030dbb116afc14
          - value: 100000
            pk: 64d48fd8a9a29571f50a2e7410b625c6509a80ac437b332d0b19ae009af15709
          - value: 1
            pk: 79b1d6e4878c1cfbf70fd8803aa49c2b1ee606cd154ecee7cf48bf7437123c1e
          - value: 100
            pk: 4dea183ece7b9061ad75c734f0ff0ec3d2b8ad74935a94e4f0d16b985db2032c
          - value: 100000
            pk: 84d2bfb27e507c4589f16fa787775eefa38b0fbba245cb282262960036b9a508
          - value: 1
            pk: 90df1c7587ba2d57361484f227c31d456c55e7202f5f22156c7023dd20ea882b
          - value: 100
            pk: 203e728cc16c853a1405fd1c191da9226c10fb1aa8ffcf37a59c5fc121398e2f
          - value: 100000
            pk: 9a59843dbbacf15c47fd44e5d113cd7153c06f242c2ad0f31657d7952639e022
          - value: 1
            pk: e371e7f92e94cfb0bc31393657c246c4e316f35a28968d10e5ad4779a83bce2c
          - value: 100
            pk: 564a40297a0cef10a8f191b5ea31a27c7a8d619959b8c039ebdd834a7df24015
          - value: 18446744073709151211
            pk: d731e00126f55e9ecfb1d1bd47e599c2728e347f4a865449e133db5486233916
      - opcode: 17
        payload:
          channel_id: '0000000000000000000000000000000000000000000000000000000000000000'
          inscription:
          - 112
          - 114
          - 111
          - 99
          - 101
          - 115
          - 115
          - 95
          - 115
          - 116
          - 97
          - 114
          - 116
          - 95
          - 110
          - 111
          - 110
          - 99
          - 101
          - 61
          - 49
          - 56
          - 97
          - 54
          - 99
          - 51
          - 50
          - 52
          - 57
          - 98
          - 55
          - 52
          - 98
          - 55
          - 97
          - 48
          - 45
          - 48
          - 48
          - 48
          - 48
          - 51
          - 99
          - 57
          - 54
          - 44
          - 32
          - 116
          - 101
          - 115
          - 116
          - 95
          - 101
          - 110
          - 116
          - 114
          - 111
          - 112
          - 121
          - 61
          - 54
          - 49
          - 52
          - 52
          - 56
          - 97
          - 51
          - 98
          - 55
          - 57
          - 99
          - 102
          - 52
          - 50
          - 97
          - 49
          parent: '0000000000000000000000000000000000000000000000000000000000000000'
          signer: '0000000000000000000000000000000000000000000000000000000000000000'
      - opcode: 32
        payload:
          service_type: BN
          locators:
          - /dns4/test-0.test/udp/7001/quic-v1
          provider_id: 37f83333f9fd611e2727c8dd54ac2b3e954879497274a60a762c44a73695f830
          zk_id: 1d154e3d75961ed9893c51617f576667aedaa3da07f8fd3de703e04ae5c6ab0a
          locked_note_id: 67e06307511824ca0267e4636c16f426f107539da9803f1247087835ff4aff0e
      - opcode: 32
        payload:
          service_type: BN
          locators:
          - /dns4/test-1.test/udp/7001/quic-v1
          provider_id: 03548111a964b426874f32882d5df3bed9080219a8c88e780a1bf9fa1aee41ff
          zk_id: 73e5b5347acf42dd07a0b42242723b835bc7775bde08e50c327e137e2c04f804
          locked_note_id: e39c619c5f8ab5ef5af08e4e8735661fe61ab8e13cbb501042b3abbd1a665a14
      - opcode: 32
        payload:
          service_type: BN
          locators:
          - /dns4/test-2.test/udp/7001/quic-v1
          provider_id: c8b6f85cea02d5212e50dbf42e504acf5b80b4d025ba4f78c2b9adf4cae1d3a1
          zk_id: f06b216409e71ea0a5ed881c819ee26983d935a29f383e6f2db51a2bc89e7625
          locked_note_id: bcaa3333d411a02050a6b5c9da20dfe848400c4fe1df44657605a65f97aa6e1e
      - opcode: 32
        payload:
          service_type: BN
          locators:
          - /dns4/test-3.test/udp/7001/quic-v1
          provider_id: 94bdbf031078be62650a64c7c2186884e2143f926605e66cad64370fe0c26be8
          zk_id: 661a2fd0ddcb8aa9301d2eef7bbd2dbe18325be8bb702be64f3b5621fc7b930c
          locked_note_id: 30481112fc01d2dc7a8c2945f3d59b14c7264b3467611c10edd7e66f1f0d2c0e
      execution_gas_price: 0
      storage_gas_price: 0
    ops_proofs:
    - !ZkSig
      pi_a:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      pi_b:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      pi_c:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
    - NoProof
    - !ZkAndEd25519Sigs
      zk_sig:
        pi_a:
        - 183
        - 13
        - 124
        - 98
        - 202
        - 70
        - 58
        - 79
        - 251
        - 169
        - 198
        - 247
        - 124
        - 225
        - 5
        - 108
        - 109
        - 223
        - 66
        - 72
        - 202
        - 224
        - 162
        - 130
        - 72
        - 204
        - 71
        - 116
        - 177
        - 221
        - 166
        - 147
        pi_b:
        - 53
        - 223
        - 22
        - 253
        - 191
        - 195
        - 101
        - 204
        - 198
        - 64
        - 153
        - 83
        - 159
        - 126
        - 193
        - 143
        - 3
        - 253
        - 84
        - 211
        - 203
        - 14
        - 40
        - 64
        - 232
        - 237
        - 77
        - 30
        - 116
        - 7
        - 8
        - 38
        - 185
        - 70
        - 139
        - 13
        - 119
        - 242
        - 121
        - 141
        - 19
        - 28
        - 103
        - 175
        - 179
        - 31
        - 30
        - 27
        - 105
        - 230
        - 113
        - 17
        - 115
        - 39
        - 128
        - 163
        - 64
        - 222
        - 50
        - 112
        - 59
        - 111
        - 122
        - 156
        pi_c:
        - 130
        - 189
        - 44
        - 18
        - 216
        - 154
        - 94
        - 131
        - 188
        - 157
        - 107
        - 146
        - 10
        - 79
        - 27
        - 149
        - 3
        - 187
        - 120
        - 46
        - 77
        - 136
        - 229
        - 222
        - 216
        - 77
        - 28
        - 15
        - 236
        - 232
        - 111
        - 41
      ed25519_sig:
      - 138
      - 181
      - 140
      - 6
      - 105
      - 182
      - 158
      - 95
      - 77
      - 11
      - 118
      - 44
      - 39
      - 44
      - 170
      - 155
      - 229
      - 1
      - 255
      - 91
      - 74
      - 217
      - 94
      - 129
      - 152
      - 238
      - 107
      - 119
      - 37
      - 231
      - 203
      - 206
      - 44
      - 85
      - 111
      - 2
      - 136
      - 147
      - 197
      - 33
      - 83
      - 200
      - 161
      - 63
      - 207
      - 37
      - 64
      - 209
      - 45
      - 55
      - 17
      - 218
      - 108
      - 249
      - 8
      - 229
      - 132
      - 65
      - 196
      - 104
      - 145
      - 17
      - 37
      - 1
    - !ZkAndEd25519Sigs
      zk_sig:
        pi_a:
        - 217
        - 23
        - 209
        - 101
        - 114
        - 200
        - 233
        - 30
        - 85
        - 159
        - 78
        - 251
        - 73
        - 43
        - 50
        - 218
        - 252
        - 141
        - 83
        - 64
        - 87
        - 249
        - 1
        - 156
        - 218
        - 145
        - 223
        - 192
        - 46
        - 81
        - 181
        - 150
        pi_b:
        - 40
        - 66
        - 23
        - 200
        - 131
        - 151
        - 39
        - 116
        - 26
        - 214
        - 133
        - 62
        - 151
        - 22
        - 255
        - 61
        - 210
        - 141
        - 151
        - 71
        - 200
        - 62
        - 87
        - 242
        - 106
        - 246
        - 232
        - 16
        - 57
        - 177
        - 96
        - 1
        - 114
        - 127
        - 223
        - 91
        - 153
        - 75
        - 231
        - 6
        - 251
        - 110
        - 184
        - 125
        - 97
        - 133
        - 94
        - 84
        - 102
        - 115
        - 234
        - 164
        - 110
        - 188
        - 49
        - 29
        - 117
        - 149
        - 7
        - 148
        - 194
        - 229
        - 137
        - 173
        pi_c:
        - 181
        - 214
        - 43
        - 31
        - 154
        - 59
        - 126
        - 219
        - 176
        - 78
        - 207
        - 239
        - 11
        - 151
        - 115
        - 131
        - 155
        - 176
        - 84
        - 6
        - 24
        - 90
        - 227
        - 109
        - 57
        - 157
        - 72
        - 180
        - 0
        - 117
        - 47
        - 168
      ed25519_sig:
      - 222
      - 21
      - 70
      - 234
      - 131
      - 122
      - 236
      - 165
      - 82
      - 109
      - 254
      - 36
      - 197
      - 84
      - 108
      - 224
      - 130
      - 245
      - 87
      - 143
      - 189
      - 128
      - 220
      - 38
      - 150
      - 33
      - 118
      - 185
      - 142
      - 237
      - 239
      - 165
      - 203
      - 74
      - 234
      - 126
      - 32
      - 188
      - 140
      - 86
      - 43
      - 46
      - 150
      - 142
      - 33
      - 57
      - 147
      - 90
      - 206
      - 194
      - 244
      - 109
      - 39
      - 123
      - 255
      - 243
      - 93
      - 206
      - 238
      - 88
      - 70
      - 86
      - 85
      - 1
    - !ZkAndEd25519Sigs
      zk_sig:
        pi_a:
        - 70
        - 160
        - 138
        - 58
        - 131
        - 216
        - 128
        - 237
        - 97
        - 40
        - 141
        - 219
        - 68
        - 229
        - 12
        - 234
        - 44
        - 132
        - 86
        - 66
        - 160
        - 73
        - 194
        - 230
        - 13
        - 180
        - 18
        - 113
        - 150
        - 199
        - 44
        - 34
        pi_b:
        - 110
        - 128
        - 231
        - 47
        - 166
        - 52
        - 123
        - 106
        - 127
        - 11
        - 203
        - 227
        - 93
        - 26
        - 222
        - 84
        - 78
        - 80
        - 73
        - 206
        - 44
        - 81
        - 247
        - 37
        - 8
        - 43
        - 214
        - 100
        - 36
        - 240
        - 209
        - 40
        - 207
        - 76
        - 111
        - 183
        - 142
        - 24
        - 36
        - 18
        - 15
        - 108
        - 92
        - 99
        - 111
        - 139
        - 54
        - 200
        - 29
        - 147
        - 24
        - 110
        - 212
        - 138
        - 105
        - 228
        - 72
        - 70
        - 116
        - 113
        - 89
        - 29
        - 158
        - 158
        pi_c:
        - 188
        - 32
        - 119
        - 38
        - 205
        - 220
        - 106
        - 28
        - 94
        - 198
        - 42
        - 30
        - 245
        - 47
        - 236
        - 192
        - 209
        - 101
        - 19
        - 89
        - 217
        - 203
        - 5
        - 2
        - 102
        - 227
        - 132
        - 48
        - 65
        - 103
        - 61
        - 43
      ed25519_sig:
      - 253
      - 144
      - 249
      - 101
      - 2
      - 177
      - 252
      - 38
      - 94
      - 118
      - 88
      - 32
      - 227
      - 125
      - 175
      - 121
      - 213
      - 255
      - 40
      - 228
      - 56
      - 195
      - 91
      - 67
      - 204
      - 0
      - 143
      - 87
      - 111
      - 19
      - 24
      - 213
      - 132
      - 110
      - 59
      - 152
      - 210
      - 32
      - 200
      - 111
      - 187
      - 99
      - 73
      - 182
      - 31
      - 99
      - 29
      - 132
      - 7
      - 146
      - 250
      - 173
      - 199
      - 141
      - 179
      - 2
      - 213
      - 5
      - 87
      - 129
      - 50
      - 233
      - 64
      - 15
    - !ZkAndEd25519Sigs
      zk_sig:
        pi_a:
        - 135
        - 1
        - 25
        - 137
        - 223
        - 119
        - 37
        - 193
        - 20
        - 173
        - 156
        - 37
        - 72
        - 20
        - 237
        - 194
        - 59
        - 133
        - 127
        - 190
        - 233
        - 223
        - 85
        - 246
        - 90
        - 236
        - 89
        - 131
        - 173
        - 56
        - 132
        - 16
        pi_b:
        - 102
        - 95
        - 47
        - 118
        - 57
        - 230
        - 35
        - 158
        - 228
        - 216
        - 112
        - 143
        - 207
        - 3
        - 2
        - 228
        - 27
        - 233
        - 131
        - 194
        - 127
        - 60
        - 186
        - 127
        - 33
        - 176
        - 70
        - 34
        - 153
        - 96
        - 247
        - 23
        - 100
        - 78
        - 11
        - 251
        - 1
        - 109
        - 65
        - 183
        - 50
        - 219
        - 151
        - 182
        - 178
        - 37
        - 125
        - 107
        - 224
        - 146
        - 207
        - 112
        - 252
        - 57
        - 112
        - 82
        - 130
        - 156
        - 162
        - 220
        - 56
        - 23
        - 209
        - 171
        pi_c:
        - 221
        - 116
        - 52
        - 182
        - 186
        - 220
        - 113
        - 212
        - 179
        - 138
        - 165
        - 194
        - 102
        - 168
        - 249
        - 100
        - 68
        - 113
        - 78
        - 76
        - 253
        - 22
        - 189
        - 202
        - 198
        - 5
        - 22
        - 79
        - 190
        - 153
        - 105
        - 38
      ed25519_sig:
      - 189
      - 33
      - 242
      - 68
      - 72
      - 213
      - 182
      - 94
      - 157
      - 238
      - 97
      - 173
      - 1
      - 182
      - 190
      - 18
      - 229
      - 137
      - 203
      - 158
      - 105
      - 182
      - 246
      - 248
      - 147
      - 250
      - 32
      - 35
      - 4
      - 237
      - 15
      - 81
      - 96
      - 56
      - 132
      - 143
      - 202
      - 52
      - 76
      - 159
      - 153
      - 131
      - 146
      - 162
      - 249
      - 177
      - 142
      - 246
      - 182
      - 175
      - 88
      - 1
      - 102
      - 87
      - 173
      - 20
      - 78
      - 23
      - 192
      - 238
      - 109
      - 145
      - 65
      - 11
  faucet_pk: d731e00126f55e9ecfb1d1bd47e599c2728e347f4a865449e133db5486233916
time:
  slot_duration: '1.000000000'
  chain_start_time: 2026-04-17 08:00:00.029919 +00:00:00
mempool:
  pubsub_topic: /logos-blockchain-devnet/mempool/1.0.0
