network:
  backend:
    swarm:
      host: 0.0.0.0
      port: 7000
      node_key: 25ff1947ed93b2559c95b8074b1cb492f6a42422830ec10413de2e8c39b9b240
      gossipsub:
        history_length: 5
        history_gossip: 3
        mesh_n: 6
        mesh_n_low: 5
        mesh_n_high: 12
        retain_scores: 4
        gossip_lazy: 6
        gossip_factor: 0.25
        heartbeat_initial_delay:
          secs: 5
          nanos: 0
        heartbeat_interval:
          secs: 1
          nanos: 0
        fanout_ttl:
          secs: 60
          nanos: 0
        check_explicit_peers_ticks: 300
        duplicate_cache_time:
          secs: 60
          nanos: 0
        validate_messages: false
        allow_self_origin: false
        do_px: false
        prune_peers: 0
        prune_backoff:
          secs: 60
          nanos: 0
        unsubscribe_backoff:
          secs: 10
          nanos: 0
        backoff_slack: 1
        flood_publish: true
        graft_flood_threshold:
          secs: 10
          nanos: 0
        mesh_outbound_min: 2
        opportunistic_graft_ticks: 60
        opportunistic_graft_peers: 2
        gossip_retransimission: 3
        max_messages_per_rpc: null
        max_ihave_length: 5000
        max_ihave_messages: 10
        iwant_followup_time:
          secs: 3
          nanos: 0
        published_message_ids_cache_time:
          secs: 10
          nanos: 0
      kademlia:
        query_timeout_secs: null
        replication_factor: null
        parallelism: null
        disjoint_query_paths: null
        max_packet_size: null
        kbucket_inserts: null
        caching: null
        periodic_bootstrap_interval_secs: null
      identify:
        agent_version: null
        interval_secs: null
        push_listen_addr_updates: null
        cache_size: null
        hide_listen_addrs: true
      chain_sync:
        peer_response_timeout: 60000
      nat:
        type: static
        external_address: /ip4/127.0.0.2/udp/7000/quic-v1
    initial_peers:
      - /dns4/test-0.test/udp/7000/quic-v1
      - /dns4/test-1.test/udp/7000/quic-v1
      - /dns4/test-2.test/udp/7000/quic-v1
      - /dns4/test-3.test/udp/7000/quic-v1
blend:
  non_ephemeral_signing_key_id: c8b6f85cea02d5212e50dbf42e504acf5b80b4d025ba4f78c2b9adf4cae1d3a1
  core:
    backend:
      listening_address: /ip4/0.0.0.0/udp/7001/quic-v1
      core_peering_degree:
        start: 2
        end: 3
      edge_node_connection_timeout: '1.000000000'
      max_edge_node_incoming_connections: 300
      max_dial_attempts_per_peer: 3
    zk:
      secret_key_kms_id: f06b216409e71ea0a5ed881c819ee26983d935a29f383e6f2db51a2bc89e7625
  edge:
    backend:
      max_dial_attempts_per_peer_per_message: 1
      replication_factor: 1
cryptarchia:
  service:
    bootstrap:
      prolonged_bootstrap_period: '1.000000000'
      force_bootstrap: false
      offline_grace_period:
        grace_period: '1200.000000000'
        state_recording_interval: '60.000000000'
  network:
    bootstrap:
      ibd:
        peers: []
        delay_before_new_download:
          secs: 10
          nanos: 0
    sync:
      orphan:
        max_orphan_cache_size: 1000
    network:
      max_connected_peers_to_try_download: 16
      max_discovered_peers_to_try_download: 16
  leader:
    wallet:
      max_tx_fee: 18446744073709551615
      funding_pk: 203e728cc16c853a1405fd1c191da9226c10fb1aa8ffcf37a59c5fc121398e2f
time:
  backend:
    server: pool.ntp.org:123
    client:
      timeout: '5.000000000'
      listening_interface: 0.0.0.0
    update_interval: '16.000000000'
sdp:
  declaration_id: 2aec051006d0a35c3b7d2350a3041067e9ae3deeacb50c8e58041ff7716f860d
  wallet:
    max_tx_fee: 18446744073709551615
    funding_pk: 203e728cc16c853a1405fd1c191da9226c10fb1aa8ffcf37a59c5fc121398e2f
api:
  backend:
    listen_address: 0.0.0.0:18080
    cors_origins: []
    timeout: 30
    max_body_size: 10485760
    max_concurrent_requests: 1000
  testing:
    listen_address: 127.0.0.1:20001
    cors_origins: []
    timeout: 30
    max_body_size: 10485760
    max_concurrent_requests: 1000
storage:
  backend:
    folder_name: ./db
    read_only: false
    column_family: blocks
kms:
  backend:
    keys:
      f06b216409e71ea0a5ed881c819ee26983d935a29f383e6f2db51a2bc89e7625: !Zk c5b6f88c2e222f567afeae875597ae564477304c02e95e4f45d9185172f6a610
      90df1c7587ba2d57361484f227c31d456c55e7202f5f22156c7023dd20ea882b: !Zk 626e25ff1947ed93b2559c95b8074b1c00000000000000000000000000000000
      203e728cc16c853a1405fd1c191da9226c10fb1aa8ffcf37a59c5fc121398e2f: !Zk 73647025ff1947ed93b2559c95b8074b00000000000000000000000000000000
      d731e00126f55e9ecfb1d1bd47e599c2728e347f4a865449e133db5486233916: !Zk e5514f45766d105c161f2f8ad0f94e5bd12642b57c76d259df55fb77ac2fa50e
      c8b6f85cea02d5212e50dbf42e504acf5b80b4d025ba4f78c2b9adf4cae1d3a1: !Ed25519 25ff1947ed93b2559c95b8074b1cb492f6a42422830ec10413de2e8c39b9b240
      84d2bfb27e507c4589f16fa787775eefa38b0fbba245cb282262960036b9a508: !Zk 6c6425ff1947ed93b2559c95b8074b1c00000000000000000000000000000000
wallet:
  known_keys:
    84d2bfb27e507c4589f16fa787775eefa38b0fbba245cb282262960036b9a508: 84d2bfb27e507c4589f16fa787775eefa38b0fbba245cb282262960036b9a508
    203e728cc16c853a1405fd1c191da9226c10fb1aa8ffcf37a59c5fc121398e2f: 203e728cc16c853a1405fd1c191da9226c10fb1aa8ffcf37a59c5fc121398e2f
    d731e00126f55e9ecfb1d1bd47e599c2728e347f4a865449e133db5486233916: d731e00126f55e9ecfb1d1bd47e599c2728e347f4a865449e133db5486233916
  voucher_master_key_id: 84d2bfb27e507c4589f16fa787775eefa38b0fbba245cb282262960036b9a508
tracing:
  logger:
    file:
      directory: ./state/logs
      prefix: null
    loki: null
    gelf: null
    otlp:
      endpoint: http://otel:4317/
      service_name: test-2.test
    stdout: true
    stderr: false
  tracing: None
  filter: None
  metrics: !Otlp
    endpoint: "http://otel-opentelemetry-collector.opentelemetry:4317/"
    host_identifier: "test-2"
  console: None
  level: DEBUG
state:
  base_folder: ./state
