# values.yaml
global:
  pubSubTopic: "/waku/2/rs/2/0"
  # pubSubTopic: "/waku/2/default-waku/proto"

replicaCount:
  bootstrap: 3
  nodes: 50

image:
  repository: zorlin/waku
  tag: debug-extra-nim-libp2p-logs-over-v0.31.0-with-extra-logs-mplex-perf
  pullPolicy: IfNotPresent

bootstrap:
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "768Mi"
      cpu: "400m"

nodes:
  resources:
    requests:
      memory: "64Mi"
      cpu: "150m"
    limits:
      memory: "600Mi"
      cpu: "500m"

publisher:
  enabled: true
  image:
    repository: zorlin/publisher
    tag: v0.5.0
  messageSize: 1
  delaySeconds: 10
  messageCount: 4000
  startDelay:
    enabled: false
    minutes: 5
  waitForStatefulSet:
    enabled: false
    name: {{ .Release.Name }}-nodes
    stabilityMinutes: 5

artificialLatency:
  enabled: false
  latencyMs: 50

customCommand:
  enabled: false
  command: []
  args: []
