apiVersion: v1
kind: Pod
metadata:
  name: get-filter-messages
  namespace: zerotesting
spec:
  restartPolicy: Never
  dnsConfig:
    searches:
      - zerotesting-filter.zerotesting.svc.cluster.local
  containers:
    - name: container
      image: soutullostatus/get_filter_messages:v1.0.0
      imagePullPolicy: IfNotPresent
      command:
        - sh
        - -c
        - python /app/filter_msg_retriever.py --contentTopic="/my-app/1/dst/proto" --numNodes=1000
