apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: nomos-testnet
spec:
  replicas: 1
  selector: { matchLabels: { app: prometheus } }
  template:
    metadata: { labels: { app: prometheus } }
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v3.0.1
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.retention.time=7d
            - --web.enable-otlp-receiver
          ports:
            - name: http
              containerPort: 9090
          volumeMounts:
            - name: prom-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: prom-config
          configMap:
            name: prom-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: nomos-testnet
spec:
  selector: { app: prometheus }
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP
