apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.nimlibp2p.nodes.name }}
  namespace: {{ default "zerotesting-nimlibp2p" .Values.nimlibp2p.nodes.namespace }}
spec:
  replicas: {{ .Values.nimlibp2p.nodes.replicas }}
  podManagementPolicy: "Parallel"
  serviceName: nimp2p-service
  selector:
    matchLabels:
      app: {{ default "zerotenkay" .Values.nimlibp2p.nodes.app }}
  template:
    metadata:
      labels:
        app: {{ default "zerotenkay" .Values.nimlibp2p.nodes.app }}
    spec:
      dnsConfig:
        {{- toYaml .Values.nimlibp2p.nodes.dnsConfig | nindent 8 }}
      initContainers:
        - name: slowyourroll
          image: soutullostatus/tc-container:1
          securityContext:
            capabilities:
              add: [ "NET_ADMIN" ]
          command:
            - sh
            - -c
            - tc qdisc add dev eth0 root netem delay 100ms 30ms distribution normal
      containers:
        - name: container-0
          image: {{ default "soutullostatus/dst-test-node" .Values.nimlibp2p.nodes.image.repository }}:{{ default "v1.8.0-mplex" .Values.nimlibp2p.nodes.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
            - containerPort: 8008
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "600Mi"
              cpu: "400m"
          env:
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
            {{- $envArgs := .Values.nimlibp2p.nodes.env }}
            {{- $preset := $envArgs.type | default "basic" -}}
            {{- include "env.genVars" ( dict
              "args" $envArgs.vars
              "presets" $envArgs.presets
              "preset" $preset)  | nindent 16 }}
          args:
            - {{ quote .Values.nimlibp2p.nodes.minutes }}
            - {{ quote .Values.nimlibp2p.nodes.hours }}
