FROM pearsonwhite/lc-p3:metrics-c50e9d39262a5fe17443a79a25f6437b19123416-amd AS base

# Do not use `tutorial-v1`. It is broken.
# ARG LOGOSCORE_CLI_BRANCH=5a1cf746e841e8e8a8fd48333cff55bd12c45c52
# ARG LOGOSCORE_CLI_BRANCH=tutorial-v3
ARG LOGOSCORE_CLI_BRANCH=0.2.1

ARG NIX_USER=nixuser

ARG USER=nixuser

ARG NIX_USER=nixuser
ENV USER=${NIX_USER}
ENV HOME=/home/${NIX_USER}
WORKDIR ${HOME}

WORKDIR $HOME
RUN git clone https://github.com/logos-co/logos-logoscore-cli.git
WORKDIR $HOME/logos-logoscore-cli
RUN git checkout ${LOGOSCORE_CLI_BRANCH} \
    && nix build \
    && ln -s $(realpath ./result)/bin/logoscore $HOME/bin/logoscore

ENV USER=$USER
USER $USER
WORKDIR /home/$USER
ENV HOME=/home/$USER

WORKDIR $HOME
COPY entrypoint.sh entrypoint.sh
COPY main.py main.py
ENTRYPOINT ["/bin/sh", "-c", "./entrypoint.sh"]