# FROM pearsonwhite/dst-lc-node:wip-base-amd AS base
FROM pearsonwhite/lc-p1-pkg2-bundler3 AS base

ARG DELIVERY_MODULE_BRANCH=v0.1.3

ARG NIX_USER=nixuser
ENV USER=${NIX_USER}
ENV HOME=/home/${NIX_USER}
WORKDIR ${HOME}

WORKDIR $HOME
RUN git clone https://github.com/logos-co/logos-delivery-module.git
WORKDIR $HOME/logos-delivery-module
RUN git checkout ${DELIVERY_MODULE_BRANCH} \
  && nix bundle --bundler $HOME/nix-bundle-lgx#dual . \
  && lgpm install --file logos-delivery_module-module-lgx-*/logos-delivery_module-module.lgx --modules-dir "$HOME/.logos/modules"

# You have to use dual for some reason.