FROM pearsonwhite/logos-core-dst:wip1-amd AS base

ARG USER=nixuser

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    git \
    build-essential ca-certificates \
    libssl3 \
    iproute2 \
    procps \
    ca-certificates \
    gcc-multilib \
    g++-multilib \
    libc6-dev-i386 \
    ssh \
    netcat-openbsd \
    cmake

RUN apt-get update && apt-get install -y --no-install-recommends python3 python3-pip \
    && pip install --break-system-packages kubernetes

ENV PATH=/usr/local/bin:$PATH

ENV USER=$USER
USER $USER
WORKDIR /home/$USER
ENV HOME=/home/$USER

WORKDIR $HOME
COPY entrypoint.sh entrypoint.sh
COPY main.py main.py
ENTRYPOINT ["/bin/sh", "-c", "./entrypoint.sh"]