apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nodes-0
  namespace: zerotesting
spec:
  replicas: 10
  podManagementPolicy: "Parallel"
  serviceName: zerotesting-service
  selector:
    matchLabels:
      app: zerotenkay
  template:
    metadata:
      labels:
        app: zerotenkay
    spec:
      dnsConfig:
        searches:
          - zerotesting-service.zerotesting.svc.cluster.local
      containers:
        - name: waku
          image: soutullostatus/nwaku-jq-curl:v0.35.0-rc.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8645
            - containerPort: 8008
          readinessProbe:
            httpGet:
              path: /health
              port: 8008
            successThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 1
            failureThreshold: 2
            timeoutSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "600Mi"
              cpu: "400m"
          env:
            - name: IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command:
            - sh
            - -c
            - /usr/bin/wakunode \
              --relay=true \
              --max-connections=200 \
              --rest=true \
              --rest-admin=true \
              --rest-address=0.0.0.0 \
              --discv5-discovery=false \
              --discv5-enr-auto-update=True \
              --log-level=INFO \
              --metrics-server=True \
              --metrics-server-address=0.0.0.0 \
              --nat=extip:${IP} \
              --cluster-id=2 \
              --shard=0 \
              --rendezvous=false