apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nodes
  namespace: zerotesting
spec:
  replicas: 100
  podManagementPolicy: "Parallel"
  serviceName: zerotesting-service
  selector:
    matchLabels:
      app: zerotenkay
  template:
    metadata:
      labels:
        app: zerotenkay
    spec:
      dnsConfig:
        searches:
          - zerotesting-service.zerotesting.svc.cluster.local
      volumes:
        - name: enr-data
          emptyDir: {}
      initContainers:
        - name: grabenr
          image: zorlin/getenr:v0.3.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: enr-data
              mountPath: /etc/enr
          command:
            - /app/getenr.sh
          args:
            - "3"
      containers:
        - name: waku
          image: zorlin/waku:debug-extra-nim-libp2p-logs-over-v0.31.0-with-extra-logs-mplex-perf
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8545
            - containerPort: 8008
          volumeMounts:
            - name: enr-data
              mountPath: /etc/enr
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "600Mi"
              cpu: "400m"
          env:
            - name: IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command:
            - sh
            - -c
            - |
              . /etc/enr/enr.env
              echo ENRs are $ENR1 $ENR2 $ENR3
              nice -n 19 /usr/bin/wakunode --relay=true --max-connections=50 --rest=true --rest-admin=true --rest-private=true --rest-address=0.0.0.0 --discv5-discovery=true --discv5-enr-auto-update=True --log-level=INFO --metrics-server=True --metrics-server-address=0.0.0.0 --discv5-bootstrap-node=$ENR1 --discv5-bootstrap-node=$ENR2 --discv5-bootstrap-node=$ENR3 --nat=extip:${IP} --pubsub-topic="/waku/2/kubetopic"
