apiVersion: v1
kind: Pod
metadata:
  name: publisher
  namespace: zerotesting
  labels:
    app: zerotenkay
spec:
  dnsConfig:
    searches:
      - zerotesting-service.zerotesting.svc.cluster.local
  containers:
    - name: publisher-container
      image: zorlin/publisher:v0.3.0
      imagePullPolicy: Always
      command:
        - sh
        - -c
        - /bin/sleep infinity
