apiVersion: v1
kind: Pod
metadata:
  name: publisher
  namespace: zerotesting
  labels:
    app: zerotenkay
spec:
  dnsConfig:
    searches:
      - zerotesting-service.zerotesting.svc.cluster.local
  containers:
    - name: publisher-container
      image: zorlin/publisher:v0.4.0
      imagePullPolicy: Always
      command:
        - sh
        - -c
        - python /app/traffic.py --msg-size-kbytes=50 --delay-seconds=5 --messages=4000 --debug -p "/waku/2/default-waku/proto"
