network:
  backend:
    swarm:
      host: 0.0.0.0
      port: 7000
      node_key: c0766250f5f6dc0c15cbba63f0286c24705156805200fca10f2aaa0cc332cee4
      gossipsub:
        history_length: 5
        history_gossip: 3
        mesh_n: 6
        mesh_n_low: 5
        mesh_n_high: 12
        retain_scores: 4
        gossip_lazy: 6
        gossip_factor: 0.25
        heartbeat_initial_delay:
          secs: 5
          nanos: 0
        heartbeat_interval:
          secs: 1
          nanos: 0
        fanout_ttl:
          secs: 60
          nanos: 0
        check_explicit_peers_ticks: 300
        duplicate_cache_time:
          secs: 60
          nanos: 0
        validate_messages: false
        allow_self_origin: false
        do_px: false
        prune_peers: 0
        prune_backoff:
          secs: 60
          nanos: 0
        unsubscribe_backoff:
          secs: 10
          nanos: 0
        backoff_slack: 1
        flood_publish: true
        graft_flood_threshold:
          secs: 10
          nanos: 0
        mesh_outbound_min: 2
        opportunistic_graft_ticks: 60
        opportunistic_graft_peers: 2
        gossip_retransimission: 3
        max_messages_per_rpc: null
        max_ihave_length: 5000
        max_ihave_messages: 10
        iwant_followup_time:
          secs: 3
          nanos: 0
        published_message_ids_cache_time:
          secs: 10
          nanos: 0
      kademlia:
        query_timeout_secs: null
        replication_factor: null
        parallelism: null
        disjoint_query_paths: null
        max_packet_size: null
        kbucket_inserts: null
        caching: null
        periodic_bootstrap_interval_secs: null
      identify:
        agent_version: null
        interval_secs: null
        push_listen_addr_updates: null
        cache_size: null
        hide_listen_addrs: true
      chain_sync:
        peer_response_timeout: 60000
      nat:
        type: static
        external_address: /ip4/127.0.0.9/udp/7000/quic-v1
    initial_peers:
      - /dns4/test-0.test/udp/7000/quic-v1
      - /dns4/test-1.test/udp/7000/quic-v1
      - /dns4/test-2.test/udp/7000/quic-v1
      - /dns4/test-3.test/udp/7000/quic-v1
      - /dns4/test-4.test/udp/7000/quic-v1
      - /dns4/test-5.test/udp/7000/quic-v1
      - /dns4/test-6.test/udp/7000/quic-v1
      - /dns4/test-7.test/udp/7000/quic-v1
      - /dns4/test-8.test/udp/7000/quic-v1
      - /dns4/test-9.test/udp/7000/quic-v1
blend:
  non_ephemeral_signing_key_id: 1d561b5e8de13c4637cbb4aaba35835c991736221d0fa59894a3981964daa7b3
  core:
    backend:
      listening_address: /ip4/0.0.0.0/udp/7001/quic-v1
      core_peering_degree:
        start: 2
        end: 3
      edge_node_connection_timeout: '1.000000000'
      max_edge_node_incoming_connections: 300
      max_dial_attempts_per_peer: 3
    zk:
      secret_key_kms_id: 1409cff5389053e37d49bffe537610de7b28e18d171e5fc8aa167736f4fa8310
  edge:
    backend:
      max_dial_attempts_per_peer_per_message: 1
      replication_factor: 1
cryptarchia:
  service:
    bootstrap:
      prolonged_bootstrap_period: '1.000000000'
      force_bootstrap: false
      offline_grace_period:
        grace_period: '1200.000000000'
        state_recording_interval: '60.000000000'
  network:
    bootstrap:
      ibd:
        peers: []
        delay_before_new_download:
          secs: 10
          nanos: 0
    sync:
      orphan:
        max_orphan_cache_size: 1000
    network:
      max_connected_peers_to_try_download: 16
      max_discovered_peers_to_try_download: 16
  leader:
    wallet:
      max_tx_fee: 18446744073709551615
      funding_pk: be74bb6ca5b7033878f26bf2d832077a620198deb6d33dfd71899b18294b7f07
time:
  backend:
    server: pool.ntp.org:123
    client:
      timeout: '5.000000000'
      listening_interface: 0.0.0.0
    update_interval: '16.000000000'
sdp:
  declaration_id: 57b01eef7b0746bfee32c15546e77fed21bec9b27b35b3f68816b3c3f845aa89
  wallet:
    max_tx_fee: 18446744073709551615
    funding_pk: be74bb6ca5b7033878f26bf2d832077a620198deb6d33dfd71899b18294b7f07
api:
  backend:
    listen_address: 0.0.0.0:18080
    cors_origins: []
    timeout: 30
    max_body_size: 10485760
    max_concurrent_requests: 1000
  testing:
    listen_address: 127.0.0.1:20264
    cors_origins: []
    timeout: 30
    max_body_size: 10485760
    max_concurrent_requests: 1000
storage:
  backend:
    folder_name: ./db
    read_only: false
    column_family: blocks
kms:
  backend:
    keys:
      d202b25f108e26037a69296bdb6d16f57da53f939c1436a35a51d02c25c25d24: !Zk 6c64c0766250f5f6dc0c15cbba63f02800000000000000000000000000000000
      b1868d9c0183f8cafa4c2d92b1496e246bc3da0ca06003559b3a7414da813320: !Zk 626ec0766250f5f6dc0c15cbba63f02800000000000000000000000000000000
      1d561b5e8de13c4637cbb4aaba35835c991736221d0fa59894a3981964daa7b3: !Ed25519 c0766250f5f6dc0c15cbba63f0286c24705156805200fca10f2aaa0cc332cee4
      be74bb6ca5b7033878f26bf2d832077a620198deb6d33dfd71899b18294b7f07: !Zk 736470c0766250f5f6dc0c15cbba63f000000000000000000000000000000000
      163ada18de0e607a935b621bfa9678fcf8c69b1280242851262be73a473b541c: !Zk 952b2135c29651707e95509694ecda512aa3b5ff7a9415e9e062bbe08daeef0c
      1409cff5389053e37d49bffe537610de7b28e18d171e5fc8aa167736f4fa8310: !Zk 1a561b8ed100977a8379883de17ce7e3810eb29df93db46f17c303760bef7a22
wallet:
  known_keys:
    d202b25f108e26037a69296bdb6d16f57da53f939c1436a35a51d02c25c25d24: d202b25f108e26037a69296bdb6d16f57da53f939c1436a35a51d02c25c25d24
    be74bb6ca5b7033878f26bf2d832077a620198deb6d33dfd71899b18294b7f07: be74bb6ca5b7033878f26bf2d832077a620198deb6d33dfd71899b18294b7f07
    163ada18de0e607a935b621bfa9678fcf8c69b1280242851262be73a473b541c: 163ada18de0e607a935b621bfa9678fcf8c69b1280242851262be73a473b541c
  voucher_master_key_id: d202b25f108e26037a69296bdb6d16f57da53f939c1436a35a51d02c25c25d24
tracing:
  logger:
    file:
      directory: ./state/logs
      prefix: null
    loki: null
    gelf: null
    otlp:
      endpoint: http://otel-opentelemetry-collector.opentelemetry:4317/
      authorization_header: Bearer ift-1YHBXyK0Dy6EsBzYf8DdXKPvfbJDzqjW8FyWUm
      service_name: test-9.test
    stdout: false
    stderr: false
  tracing: None
  filter: None
  metrics: !Otlp
    endpoint: http://otel-opentelemetry-collector.opentelemetry:4317/
    authorization_header: Bearer ift-1YHBXyK0Dy6EsBzYf8DdXKPvfbJDzqjW8FyWUm
    host_identifier: test-9.test
  console: None
  level: TRACE
state:
  base_folder: ./state
