kubectl cp -n test deployment-settings.yaml test-0:/data/volumes/nomos/test/
kubectl cp -n test user_config_0.yaml test-0:/data/volumes/nomos/test/
kubectl cp -n test user_config_1.yaml test-0:/data/volumes/nomos/test/
kubectl cp -n test user_config_2.yaml test-0:/data/volumes/nomos/test/
kubectl cp -n test user_config_3.yaml test-0:/data/volumes/nomos/test/
kubectl cp -n test user_config_4.yaml test-0:/data/volumes/nomos/test/
kubectl cp -n test user_config_5.yaml test-0:/data/volumes/nomos/test/
kubectl cp -n test user_config_6.yaml test-0:/data/volumes/nomos/test/
kubectl cp -n test user_config_7.yaml test-0:/data/volumes/nomos/test/
kubectl cp -n test user_config_8.yaml test-0:/data/volumes/nomos/test/
kubectl cp -n test user_config_9.yaml test-0:/data/volumes/nomos/test/
kubectl cp -n test user_config_10.yaml test-0:/data/volumes/nomos/test/
kubectl cp -n test user_config_11.yaml test-0:/data/volumes/nomos/test/
kubectl cp -n test user_config_12.yaml test-0:/data/volumes/nomos/test/
kubectl cp -n test user_config_13.yaml test-0:/data/volumes/nomos/test/
kubectl cp -n test user_config_14.yaml test-0:/data/volumes/nomos/test/
kubectl cp -n test user_config_15.yaml test-0:/data/volumes/nomos/test/

kubectl cp -n test deployment-settings.yaml test-1:/data/volumes/nomos/test/
kubectl cp -n test user_config_0.yaml test-1:/data/volumes/nomos/test/
kubectl cp -n test user_config_1.yaml test-1:/data/volumes/nomos/test/
kubectl cp -n test user_config_2.yaml test-1:/data/volumes/nomos/test/
kubectl cp -n test user_config_3.yaml test-1:/data/volumes/nomos/test/
kubectl cp -n test user_config_4.yaml test-1:/data/volumes/nomos/test/
kubectl cp -n test user_config_5.yaml test-1:/data/volumes/nomos/test/
kubectl cp -n test user_config_6.yaml test-1:/data/volumes/nomos/test/
kubectl cp -n test user_config_7.yaml test-1:/data/volumes/nomos/test/
kubectl cp -n test user_config_8.yaml test-1:/data/volumes/nomos/test/
kubectl cp -n test user_config_9.yaml test-1:/data/volumes/nomos/test/
kubectl cp -n test user_config_10.yaml test-1:/data/volumes/nomos/test/
kubectl cp -n test user_config_11.yaml test-1:/data/volumes/nomos/test/
kubectl cp -n test user_config_12.yaml test-1:/data/volumes/nomos/test/
kubectl cp -n test user_config_13.yaml test-1:/data/volumes/nomos/test/
kubectl cp -n test user_config_14.yaml test-1:/data/volumes/nomos/test/
kubectl cp -n test user_config_15.yaml test-1:/data/volumes/nomos/test/

kubectl cp -n test deployment-settings.yaml test-2:/data/volumes/nomos/test/
kubectl cp -n test user_config_0.yaml test-2:/data/volumes/nomos/test/
kubectl cp -n test user_config_1.yaml test-2:/data/volumes/nomos/test/
kubectl cp -n test user_config_2.yaml test-2:/data/volumes/nomos/test/
kubectl cp -n test user_config_3.yaml test-2:/data/volumes/nomos/test/
kubectl cp -n test user_config_4.yaml test-2:/data/volumes/nomos/test/
kubectl cp -n test user_config_5.yaml test-2:/data/volumes/nomos/test/
kubectl cp -n test user_config_6.yaml test-2:/data/volumes/nomos/test/
kubectl cp -n test user_config_7.yaml test-2:/data/volumes/nomos/test/
kubectl cp -n test user_config_8.yaml test-2:/data/volumes/nomos/test/
kubectl cp -n test user_config_9.yaml test-2:/data/volumes/nomos/test/
kubectl cp -n test user_config_10.yaml test-2:/data/volumes/nomos/test/
kubectl cp -n test user_config_11.yaml test-2:/data/volumes/nomos/test/
kubectl cp -n test user_config_12.yaml test-2:/data/volumes/nomos/test/
kubectl cp -n test user_config_13.yaml test-2:/data/volumes/nomos/test/
kubectl cp -n test user_config_14.yaml test-2:/data/volumes/nomos/test/
kubectl cp -n test user_config_15.yaml test-2:/data/volumes/nomos/test/

kubectl cp -n test deployment-settings.yaml test-5:/data/volumes/nomos/test/
kubectl cp -n test user_config_0.yaml test-5:/data/volumes/nomos/test/
kubectl cp -n test user_config_1.yaml test-5:/data/volumes/nomos/test/
kubectl cp -n test user_config_2.yaml test-5:/data/volumes/nomos/test/
kubectl cp -n test user_config_3.yaml test-5:/data/volumes/nomos/test/
kubectl cp -n test user_config_4.yaml test-5:/data/volumes/nomos/test/
kubectl cp -n test user_config_5.yaml test-5:/data/volumes/nomos/test/
kubectl cp -n test user_config_6.yaml test-5:/data/volumes/nomos/test/
kubectl cp -n test user_config_7.yaml test-5:/data/volumes/nomos/test/
kubectl cp -n test user_config_8.yaml test-5:/data/volumes/nomos/test/
kubectl cp -n test user_config_9.yaml test-5:/data/volumes/nomos/test/
kubectl cp -n test user_config_10.yaml test-5:/data/volumes/nomos/test/
kubectl cp -n test user_config_11.yaml test-5:/data/volumes/nomos/test/
kubectl cp -n test user_config_12.yaml test-5:/data/volumes/nomos/test/
kubectl cp -n test user_config_13.yaml test-5:/data/volumes/nomos/test/
kubectl cp -n test user_config_14.yaml test-5:/data/volumes/nomos/test/
kubectl cp -n test user_config_15.yaml test-5:/data/volumes/nomos/test/

kubectl cp -n test deployment-settings.yaml test-4:/data/volumes/nomos/test/
kubectl cp -n test user_config_0.yaml test-4:/data/volumes/nomos/test/
kubectl cp -n test user_config_1.yaml test-4:/data/volumes/nomos/test/
kubectl cp -n test user_config_2.yaml test-4:/data/volumes/nomos/test/
kubectl cp -n test user_config_3.yaml test-4:/data/volumes/nomos/test/
kubectl cp -n test user_config_4.yaml test-4:/data/volumes/nomos/test/
kubectl cp -n test user_config_5.yaml test-4:/data/volumes/nomos/test/
kubectl cp -n test user_config_6.yaml test-4:/data/volumes/nomos/test/
kubectl cp -n test user_config_7.yaml test-4:/data/volumes/nomos/test/
kubectl cp -n test user_config_8.yaml test-4:/data/volumes/nomos/test/
kubectl cp -n test user_config_9.yaml test-4:/data/volumes/nomos/test/
kubectl cp -n test user_config_10.yaml test-4:/data/volumes/nomos/test/
kubectl cp -n test user_config_11.yaml test-4:/data/volumes/nomos/test/
kubectl cp -n test user_config_12.yaml test-4:/data/volumes/nomos/test/
kubectl cp -n test user_config_13.yaml test-4:/data/volumes/nomos/test/
kubectl cp -n test user_config_14.yaml test-4:/data/volumes/nomos/test/
kubectl cp -n test user_config_15.yaml test-4:/data/volumes/nomos/test/