network:
  backend:
    swarm:
      host: 0.0.0.0
      port: 7000
      node_key: 23978531e21c89dc493b64e1fe3cbd21da68b7fdbe661e59695d9b4e616f0152
      gossipsub:
        history_length: 5
        history_gossip: 3
        mesh_n: 6
        mesh_n_low: 5
        mesh_n_high: 12
        retain_scores: 4
        gossip_lazy: 6
        gossip_factor: 0.25
        heartbeat_initial_delay:
          secs: 5
          nanos: 0
        heartbeat_interval:
          secs: 1
          nanos: 0
        fanout_ttl:
          secs: 60
          nanos: 0
        check_explicit_peers_ticks: 300
        duplicate_cache_time:
          secs: 60
          nanos: 0
        validate_messages: false
        allow_self_origin: false
        do_px: false
        prune_peers: 0
        prune_backoff:
          secs: 60
          nanos: 0
        unsubscribe_backoff:
          secs: 10
          nanos: 0
        backoff_slack: 1
        flood_publish: true
        graft_flood_threshold:
          secs: 10
          nanos: 0
        mesh_outbound_min: 2
        opportunistic_graft_ticks: 60
        opportunistic_graft_peers: 2
        gossip_retransimission: 3
        max_messages_per_rpc: null
        max_ihave_length: 5000
        max_ihave_messages: 10
        iwant_followup_time:
          secs: 3
          nanos: 0
        published_message_ids_cache_time:
          secs: 10
          nanos: 0
      kademlia:
        query_timeout_secs: null
        replication_factor: null
        parallelism: null
        disjoint_query_paths: null
        max_packet_size: null
        kbucket_inserts: null
        caching: null
        periodic_bootstrap_interval_secs: null
      identify:
        agent_version: null
        interval_secs: null
        push_listen_addr_updates: null
        cache_size: null
        hide_listen_addrs: true
      chain_sync:
        peer_response_timeout: 60000
      nat:
        type: static
        external_address: /ip4/127.0.0.4/udp/7000/quic-v1
    initial_peers:
      - /dns4/test-0.test/udp/7000/quic-v1
      - /dns4/test-1.test/udp/7000/quic-v1
      - /dns4/test-2.test/udp/7000/quic-v1
      - /dns4/test-3.test/udp/7000/quic-v1
      - /dns4/test-4.test/udp/7000/quic-v1
      - /dns4/test-5.test/udp/7000/quic-v1
      - /dns4/test-6.test/udp/7000/quic-v1
      - /dns4/test-7.test/udp/7000/quic-v1
      - /dns4/test-8.test/udp/7000/quic-v1
      - /dns4/test-9.test/udp/7000/quic-v1
blend:
  non_ephemeral_signing_key_id: a5b5627429210cd4de03786fbe08ebafe141c6f569328cbd3acb2a9fc76aa7fd
  core:
    backend:
      listening_address: /ip4/0.0.0.0/udp/7001/quic-v1
      core_peering_degree:
        start: 3
        end: 5
      edge_node_connection_timeout: '1.000000000'
      max_edge_node_incoming_connections: 300
      max_dial_attempts_per_peer: 3
    zk:
      secret_key_kms_id: e00c753b3566cb4ff9cf2823ce8ecef16bcb9e7688f6c2c777001552b7aed621
  edge:
    backend:
      max_dial_attempts_per_peer_per_message: 1
      replication_factor: 1
cryptarchia:
  service:
    bootstrap:
      prolonged_bootstrap_period: '1.000000000'
      force_bootstrap: false
      offline_grace_period:
        grace_period: '1200.000000000'
        state_recording_interval: '60.000000000'
  network:
    bootstrap:
      ibd:
        peers: []
        delay_before_new_download:
          secs: 10
          nanos: 0
    sync:
      orphan:
        max_orphan_cache_size: 1000
    network:
      max_connected_peers_to_try_download: 16
      max_discovered_peers_to_try_download: 16
  leader:
    wallet:
      max_tx_fee: 18446744073709551615
      funding_pk: 4fbb11747f1e66be88027e92d0cd214dd906b34a7002f6186da10bf8b206b113
time:
  backend:
    server: pool.ntp.org:123
    client:
      timeout: '5.000000000'
      listening_interface: 0.0.0.0
    update_interval: '16.000000000'
sdp:
  declaration_id: 0eb7bc68eaedb06029af71a0accbb17c5f983416eb61aee8db7643c4e2d589f4
  wallet:
    max_tx_fee: 18446744073709551615
    funding_pk: 4fbb11747f1e66be88027e92d0cd214dd906b34a7002f6186da10bf8b206b113
api:
  backend:
    listen_address: 0.0.0.0:18080
    cors_origins: []
    timeout: 30
    max_body_size: 10485760
    max_concurrent_requests: 1000
  testing:
    listen_address: 127.0.0.1:20009
    cors_origins: []
    timeout: 30
    max_body_size: 10485760
    max_concurrent_requests: 1000
storage:
  backend:
    folder_name: ./db
    read_only: false
    column_family: blocks
kms:
  backend:
    keys:
      e00c753b3566cb4ff9cf2823ce8ecef16bcb9e7688f6c2c777001552b7aed621: !Zk a0b562c44555a28008d1d80e547fe7e60f883f6ed9d5fa236aaa323989e2b10b
      d1850a704bb70f96cac333ed4514b2ee39f6594fb8b9ccbec86c3dc01c86a32f: !Zk 6c6423978531e21c89dc493b64e1fe3c00000000000000000000000000000000
      4fbb11747f1e66be88027e92d0cd214dd906b34a7002f6186da10bf8b206b113: !Zk 73647023978531e21c89dc493b64e1fe00000000000000000000000000000000
      a5b5627429210cd4de03786fbe08ebafe141c6f569328cbd3acb2a9fc76aa7fd: !Ed25519 23978531e21c89dc493b64e1fe3cbd21da68b7fdbe661e59695d9b4e616f0152
      d731e00126f55e9ecfb1d1bd47e599c2728e347f4a865449e133db5486233916: !Zk e5514f45766d105c161f2f8ad0f94e5bd12642b57c76d259df55fb77ac2fa50e
      64640e4ca96045de797894b8a39ca5716a25884305b96281631e48ca19c24627: !Zk 626e23978531e21c89dc493b64e1fe3c00000000000000000000000000000000
wallet:
  known_keys:
    4fbb11747f1e66be88027e92d0cd214dd906b34a7002f6186da10bf8b206b113: 4fbb11747f1e66be88027e92d0cd214dd906b34a7002f6186da10bf8b206b113
    d1850a704bb70f96cac333ed4514b2ee39f6594fb8b9ccbec86c3dc01c86a32f: d1850a704bb70f96cac333ed4514b2ee39f6594fb8b9ccbec86c3dc01c86a32f
    d731e00126f55e9ecfb1d1bd47e599c2728e347f4a865449e133db5486233916: d731e00126f55e9ecfb1d1bd47e599c2728e347f4a865449e133db5486233916
  voucher_master_key_id: d1850a704bb70f96cac333ed4514b2ee39f6594fb8b9ccbec86c3dc01c86a32f
tracing:
  logger:
    file:
      directory: ./state/logs
      prefix: null
    loki: null
    gelf: null
    otlp:
      endpoint: http://otel:4317/
      service_name: node-genesis-4.nomos-genesis
    stdout: true
    stderr: false
  tracing: None
  filter: None
  metrics: !Otlp
    endpoint: "http://otel-opentelemetry-collector.opentelemetry:4317/"
    host_identifier: "test-4"
  console: None
  level: DEBUG
state:
  base_folder: ./state
