network:
  backend:
    swarm:
      host: 0.0.0.0
      port: 7000
      node_key: 55a59ec609a5d33c7637c4850edef736bc8a2bb4b1041646cb49da0fc7d1df41
      gossipsub:
        history_length: 5
        history_gossip: 3
        mesh_n: 6
        mesh_n_low: 5
        mesh_n_high: 12
        retain_scores: 4
        gossip_lazy: 6
        gossip_factor: 0.25
        heartbeat_initial_delay:
          secs: 5
          nanos: 0
        heartbeat_interval:
          secs: 1
          nanos: 0
        fanout_ttl:
          secs: 60
          nanos: 0
        check_explicit_peers_ticks: 300
        duplicate_cache_time:
          secs: 60
          nanos: 0
        validate_messages: false
        allow_self_origin: false
        do_px: false
        prune_peers: 0
        prune_backoff:
          secs: 60
          nanos: 0
        unsubscribe_backoff:
          secs: 10
          nanos: 0
        backoff_slack: 1
        flood_publish: true
        graft_flood_threshold:
          secs: 10
          nanos: 0
        mesh_outbound_min: 2
        opportunistic_graft_ticks: 60
        opportunistic_graft_peers: 2
        gossip_retransimission: 3
        max_messages_per_rpc: null
        max_ihave_length: 5000
        max_ihave_messages: 10
        iwant_followup_time:
          secs: 3
          nanos: 0
        published_message_ids_cache_time:
          secs: 10
          nanos: 0
      kademlia:
        query_timeout_secs: null
        replication_factor: null
        parallelism: null
        disjoint_query_paths: null
        max_packet_size: null
        kbucket_inserts: null
        caching: null
        periodic_bootstrap_interval_secs: null
      identify:
        agent_version: null
        interval_secs: null
        push_listen_addr_updates: null
        cache_size: null
        hide_listen_addrs: true
      chain_sync:
        peer_response_timeout: 60000
      nat:
        type: static
        external_address: /ip4/127.0.0.6/udp/7000/quic-v1
    initial_peers:
      - /dns4/test-0.test/udp/7000/quic-v1
      - /dns4/test-1.test/udp/7000/quic-v1
      - /dns4/test-2.test/udp/7000/quic-v1
      - /dns4/test-3.test/udp/7000/quic-v1
      - /dns4/test-4.test/udp/7000/quic-v1
      - /dns4/test-5.test/udp/7000/quic-v1
      - /dns4/test-6.test/udp/7000/quic-v1
      - /dns4/test-7.test/udp/7000/quic-v1
      - /dns4/test-8.test/udp/7000/quic-v1
      - /dns4/test-9.test/udp/7000/quic-v1
blend:
  non_ephemeral_signing_key_id: 2e9993f543f6f23b265c1a9a5d183d93bc0dfb518bf85a035f21f75099da363f
  core:
    backend:
      listening_address: /ip4/0.0.0.0/udp/7001/quic-v1
      core_peering_degree:
        start: 3
        end: 5
      edge_node_connection_timeout: '1.000000000'
      max_edge_node_incoming_connections: 300
      max_dial_attempts_per_peer: 3
    zk:
      secret_key_kms_id: f95479c46a0d4a474e83c8ac21ae5a951f41845002a079bd2ef29b8d5c20991e
  edge:
    backend:
      max_dial_attempts_per_peer_per_message: 1
      replication_factor: 1
cryptarchia:
  service:
    bootstrap:
      prolonged_bootstrap_period: '1.000000000'
      force_bootstrap: false
      offline_grace_period:
        grace_period: '1200.000000000'
        state_recording_interval: '60.000000000'
  network:
    bootstrap:
      ibd:
        peers: []
        delay_before_new_download:
          secs: 10
          nanos: 0
    sync:
      orphan:
        max_orphan_cache_size: 1000
    network:
      max_connected_peers_to_try_download: 16
      max_discovered_peers_to_try_download: 16
  leader:
    wallet:
      max_tx_fee: 18446744073709551615
      funding_pk: f30f0efacdb77b8783ac7f19384331d1e711818bb8a14bb30e1eba360eeb0117
time:
  backend:
    server: pool.ntp.org:123
    client:
      timeout: '5.000000000'
      listening_interface: 0.0.0.0
    update_interval: '16.000000000'
sdp:
  declaration_id: b5006115aed6fccdca6f0c12aa2c40619834b388e9c2aff9ed1703c0e6196b6f
  wallet:
    max_tx_fee: 18446744073709551615
    funding_pk: f30f0efacdb77b8783ac7f19384331d1e711818bb8a14bb30e1eba360eeb0117
api:
  backend:
    listen_address: 0.0.0.0:18080
    cors_origins: []
    timeout: 30
    max_body_size: 10485760
    max_concurrent_requests: 1000
  testing:
    listen_address: 127.0.0.1:20003
    cors_origins: []
    timeout: 30
    max_body_size: 10485760
    max_concurrent_requests: 1000
storage:
  backend:
    folder_name: ./db
    read_only: false
    column_family: blocks
kms:
  backend:
    keys:
      f95479c46a0d4a474e83c8ac21ae5a951f41845002a079bd2ef29b8d5c20991e: !Zk 2d999305b00011f894eb60201530096b5fb579d0d4b20a4b3581c56f268cd20e
      f30f0efacdb77b8783ac7f19384331d1e711818bb8a14bb30e1eba360eeb0117: !Zk 73647055a59ec609a5d33c7637c4850e00000000000000000000000000000000
      d731e00126f55e9ecfb1d1bd47e599c2728e347f4a865449e133db5486233916: !Zk e5514f45766d105c161f2f8ad0f94e5bd12642b57c76d259df55fb77ac2fa50e
      2e9993f543f6f23b265c1a9a5d183d93bc0dfb518bf85a035f21f75099da363f: !Ed25519 55a59ec609a5d33c7637c4850edef736bc8a2bb4b1041646cb49da0fc7d1df41
      844d6196dd1808e330800fdd5473c760694dd971b271581b85d0842ecaa7b72f: !Zk 626e55a59ec609a5d33c7637c4850ede00000000000000000000000000000000
      9b6cb2a6b04719173e1adea342dbf4b7fcbf0fb13e3eefe7a61a28cbc80f0915: !Zk 6c6455a59ec609a5d33c7637c4850ede00000000000000000000000000000000
wallet:
  known_keys:
    9b6cb2a6b04719173e1adea342dbf4b7fcbf0fb13e3eefe7a61a28cbc80f0915: 9b6cb2a6b04719173e1adea342dbf4b7fcbf0fb13e3eefe7a61a28cbc80f0915
    d731e00126f55e9ecfb1d1bd47e599c2728e347f4a865449e133db5486233916: d731e00126f55e9ecfb1d1bd47e599c2728e347f4a865449e133db5486233916
    f30f0efacdb77b8783ac7f19384331d1e711818bb8a14bb30e1eba360eeb0117: f30f0efacdb77b8783ac7f19384331d1e711818bb8a14bb30e1eba360eeb0117
  voucher_master_key_id: 9b6cb2a6b04719173e1adea342dbf4b7fcbf0fb13e3eefe7a61a28cbc80f0915
tracing:
  logger:
    file:
      directory: ./state/logs
      prefix: null
    loki: null
    gelf: null
    otlp:
      endpoint: http://otel:4317/
      service_name: node-genesis-6.nomos-genesis
    stdout: true
    stderr: false
  tracing: None
  filter: None
  metrics: !Otlp
    endpoint: "http://otel-opentelemetry-collector.opentelemetry:4317/"
    host_identifier: "test-6"
  console: None
  level: DEBUG
state:
  base_folder: ./state
