network:
  backend:
    swarm:
      host: 0.0.0.0
      port: 7000
      node_key: d7bf48eefc192f6202b88657344ac5a82d58c55bc8d7e755b80c6193e326a074
      gossipsub:
        history_length: 5
        history_gossip: 3
        mesh_n: 6
        mesh_n_low: 5
        mesh_n_high: 12
        retain_scores: 4
        gossip_lazy: 6
        gossip_factor: 0.25
        heartbeat_initial_delay:
          secs: 5
          nanos: 0
        heartbeat_interval:
          secs: 1
          nanos: 0
        fanout_ttl:
          secs: 60
          nanos: 0
        check_explicit_peers_ticks: 300
        duplicate_cache_time:
          secs: 60
          nanos: 0
        validate_messages: false
        allow_self_origin: false
        do_px: false
        prune_peers: 0
        prune_backoff:
          secs: 60
          nanos: 0
        unsubscribe_backoff:
          secs: 10
          nanos: 0
        backoff_slack: 1
        flood_publish: true
        graft_flood_threshold:
          secs: 10
          nanos: 0
        mesh_outbound_min: 2
        opportunistic_graft_ticks: 60
        opportunistic_graft_peers: 2
        gossip_retransimission: 3
        max_messages_per_rpc: null
        max_ihave_length: 5000
        max_ihave_messages: 10
        iwant_followup_time:
          secs: 3
          nanos: 0
        published_message_ids_cache_time:
          secs: 10
          nanos: 0
      kademlia:
        query_timeout_secs: null
        replication_factor: null
        parallelism: null
        disjoint_query_paths: null
        max_packet_size: null
        kbucket_inserts: null
        caching: null
        periodic_bootstrap_interval_secs: null
      identify:
        agent_version: null
        interval_secs: null
        push_listen_addr_updates: null
        cache_size: null
        hide_listen_addrs: true
      chain_sync:
        peer_response_timeout: 60000
      nat:
        type: static
        external_address: /ip4/127.0.0.9/udp/7000/quic-v1
    initial_peers:
      - /dns4/node-genesis-0.nomos-genesis/udp/7000/quic-v1
      - /dns4/node-genesis-1.nomos-genesis/udp/7000/quic-v1
      - /dns4/node-genesis-2.nomos-genesis/udp/7000/quic-v1
      - /dns4/node-genesis-3.nomos-genesis/udp/7000/quic-v1
      - /dns4/node-genesis-4.nomos-genesis/udp/7000/quic-v1
      - /dns4/node-genesis-5.nomos-genesis/udp/7000/quic-v1
      - /dns4/node-genesis-6.nomos-genesis/udp/7000/quic-v1
      - /dns4/node-genesis-7.nomos-genesis/udp/7000/quic-v1
      - /dns4/node-genesis-8.nomos-genesis/udp/7000/quic-v1
      - /dns4/node-genesis-9.nomos-genesis/udp/7000/quic-v1
blend:
  non_ephemeral_signing_key_id: 4008cd12eec1e7379a5f2ab9c6ee514a1be388206abff98845f009aff418d490
  core:
    backend:
      listening_address: /ip4/0.0.0.0/udp/7001/quic-v1
      core_peering_degree:
        start: 2
        end: 3
      edge_node_connection_timeout: '1.000000000'
      max_edge_node_incoming_connections: 300
      max_dial_attempts_per_peer: 3
    zk:
      secret_key_kms_id: 934f23839e58d66d331d1e1794986b3c938add589ba2328cb8b4058982783f1a
  edge:
    backend:
      max_dial_attempts_per_peer_per_message: 1
      replication_factor: 1
cryptarchia:
  service:
    bootstrap:
      prolonged_bootstrap_period: '1.000000000'
      force_bootstrap: false
      offline_grace_period:
        grace_period: '1200.000000000'
        state_recording_interval: '60.000000000'
  network:
    bootstrap:
      ibd:
        peers: []
        delay_before_new_download:
          secs: 10
          nanos: 0
    sync:
      orphan:
        max_orphan_cache_size: 1000
    network:
      max_connected_peers_to_try_download: 16
      max_discovered_peers_to_try_download: 16
  leader:
    wallet:
      max_tx_fee: 18446744073709551615
      funding_pk: 3396f032ebcaa39b4388a7034527d413cd223f84b4fee5ede15f4d79f964ef0f
time:
  backend:
    server: pool.ntp.org:123
    client:
      timeout: '5.000000000'
      listening_interface: 0.0.0.0
    update_interval: '16.000000000'
sdp:
  declaration_id: 6b3ce8b714b3a08b9f477a00af0739c7fc33119a4c013458b50df40a9d09a23a
  wallet:
    max_tx_fee: 18446744073709551615
    funding_pk: 3396f032ebcaa39b4388a7034527d413cd223f84b4fee5ede15f4d79f964ef0f
api:
  backend:
    listen_address: 0.0.0.0:18080
    cors_origins: []
    timeout: 30
    max_body_size: 10485760
    max_concurrent_requests: 1000
  testing:
    listen_address: 127.0.0.1:20005
    cors_origins: []
    timeout: 30
    max_body_size: 10485760
    max_concurrent_requests: 1000
storage:
  backend:
    folder_name: ./db
    read_only: false
    column_family: blocks
kms:
  backend:
    keys:
      4008cd12eec1e7379a5f2ab9c6ee514a1be388206abff98845f009aff418d490: !Ed25519 4fb7fa3bf5a7886a956c58c29592dfd6d9feb8d797dfee72617ddfffa19a7115
      492722c83899d2aea3c060a3e014b5798b947e270acd6dd0c9cea4996e6e1b22: !Zk 626ed2eb4de74d01912b541a3ee3ca4600000000000000000000000000000000
      d731e00126f55e9ecfb1d1bd47e599c2728e347f4a865449e133db5486233916: !Zk e5514f45766d105c161f2f8ad0f94e5bd12642b57c76d259df55fb77ac2fa50e
      bd21d21bc0682ae100b53173af962268c044a6a10573a6111dbb8e43f7777219: !Zk 6c64d2eb4de74d01912b541a3ee3ca4600000000000000000000000000000000
      3396f032ebcaa39b4388a7034527d413cd223f84b4fee5ede15f4d79f964ef0f: !Zk 736470d2eb4de74d01912b541a3ee3ca00000000000000000000000000000000
      934f23839e58d66d331d1e1794986b3c938add589ba2328cb8b4058982783f1a: !Zk 3e08cd32c6d623b0777eb7c5351eeaf96032861dfd335918f2afa6ec0e7c0b30
wallet:
  known_keys:
    3396f032ebcaa39b4388a7034527d413cd223f84b4fee5ede15f4d79f964ef0f: 3396f032ebcaa39b4388a7034527d413cd223f84b4fee5ede15f4d79f964ef0f
    bd21d21bc0682ae100b53173af962268c044a6a10573a6111dbb8e43f7777219: bd21d21bc0682ae100b53173af962268c044a6a10573a6111dbb8e43f7777219
    d731e00126f55e9ecfb1d1bd47e599c2728e347f4a865449e133db5486233916: d731e00126f55e9ecfb1d1bd47e599c2728e347f4a865449e133db5486233916
  voucher_master_key_id: bd21d21bc0682ae100b53173af962268c044a6a10573a6111dbb8e43f7777219
tracing:
  logger:
    file:
      directory: ./state/logs
      prefix: null
    loki: null
    gelf: null
    otlp:
      endpoint: http://otel:4317/
      service_name: node-genesis-9.nomos-genesis
    stdout: true
    stderr: false
  tracing: None
  filter: None
  metrics: !Otlp
    endpoint: "http://otel-opentelemetry-collector.opentelemetry:4317/"
    host_identifier: "node-genesis-10"
  console: None
  level: DEBUG
state:
  base_folder: ./state
