apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lpclient-0
  namespace: zerotesting
spec:
  replicas: 500
  podManagementPolicy: "Parallel"
  serviceName: zerotesting-lightpush-client
  selector:
    matchLabels:
      app: zerotenkay-lightpush-client
  template:
    metadata:
      labels:
        app: zerotenkay-lightpush-client
    spec:
      volumes:
        - name: address-data
          emptyDir: {}
      initContainers:
        - name: grabaddress
          image: soutullostatus/getaddress:v0.1.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: address-data
              mountPath: /etc/addrs
          command:
            - /app/getaddress.sh
          args:
            - "1"
            - "zerotesting-lightpush-server.zerotesting"
      containers:
        - name: waku
          image: soutullostatus/nwaku-jq-curl:v0.34.0-rc1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8645
            - containerPort: 8008
          volumeMounts:
            - name: address-data
              mountPath: /etc/addrs
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - >
                  if curl -s http://127.0.0.1:8008/health | grep -q 'OK'; then
                    exit 0;  # success, healthy state
                  else
                    exit 1;  # failure, unhealthy state
                  fi
            successThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 1
            failureThreshold: 2
            timeoutSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "600Mi"
              cpu: "400m"
          env:
            - name: IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command:
            - sh
            - -c
            - |
              . /etc/addrs/addrs.env
              echo addrs are $addrs1
              nice -n 19 /usr/bin/wakunode --lightpushnode=$addrs1 --relay=false --rest=true --rest-admin=true --rest-address=0.0.0.0 --log-level=INFO --metrics-server=True --metrics-server-address=0.0.0.0 --nat=extip:${IP} --cluster-id=2 --shard=0