network:
  backend:
    swarm:
      host: 0.0.0.0
      port: 7000
      node_key: 7f832b3b8fee49adc02c09c12085d81555739a1a64b7a438654cf32c5ad14725
      gossipsub:
        history_length: 5
        history_gossip: 3
        mesh_n: 6
        mesh_n_low: 5
        mesh_n_high: 12
        retain_scores: 4
        gossip_lazy: 6
        gossip_factor: 0.25
        heartbeat_initial_delay:
          secs: 5
          nanos: 0
        heartbeat_interval:
          secs: 1
          nanos: 0
        fanout_ttl:
          secs: 60
          nanos: 0
        check_explicit_peers_ticks: 300
        duplicate_cache_time:
          secs: 60
          nanos: 0
        validate_messages: false
        allow_self_origin: false
        do_px: false
        prune_peers: 0
        prune_backoff:
          secs: 60
          nanos: 0
        unsubscribe_backoff:
          secs: 10
          nanos: 0
        backoff_slack: 1
        flood_publish: true
        graft_flood_threshold:
          secs: 10
          nanos: 0
        mesh_outbound_min: 2
        opportunistic_graft_ticks: 60
        opportunistic_graft_peers: 2
        gossip_retransimission: 3
        max_messages_per_rpc: null
        max_ihave_length: 5000
        max_ihave_messages: 10
        iwant_followup_time:
          secs: 3
          nanos: 0
        published_message_ids_cache_time:
          secs: 10
          nanos: 0
      kademlia:
        query_timeout_secs: null
        replication_factor: null
        parallelism: null
        disjoint_query_paths: null
        max_packet_size: null
        kbucket_inserts: null
        caching: null
        periodic_bootstrap_interval_secs: null
      identify:
        agent_version: null
        interval_secs: null
        push_listen_addr_updates: null
        cache_size: null
        hide_listen_addrs: true
      chain_sync:
        peer_response_timeout: 60000
      nat:
        type: static
        external_address: /ip4/127.0.0.3/udp/7000/quic-v1
    initial_peers:
    - /dns4/node-genesis-0.nomos-genesis/udp/7000/quic-v1
    - /dns4/node-genesis-1.nomos-genesis/udp/7000/quic-v1
    - /dns4/node-genesis-2.nomos-genesis/udp/7000/quic-v1
    - /dns4/node-genesis-3.nomos-genesis/udp/7000/quic-v1
blend:
  non_ephemeral_signing_key_id: 5843e4daf0fc941ad665275b37223f7054e2d215a5acf340d2a313574409f597
  core:
    backend:
      listening_address: /ip4/0.0.0.0/udp/7001/quic-v1
      core_peering_degree:
        start: 2
        end: 3
      edge_node_connection_timeout: '1.000000000'
      max_edge_node_incoming_connections: 300
      max_dial_attempts_per_peer: 3
    zk:
      secret_key_kms_id: a530cc60636fb43a23f11f40fd4b73724f6bb6ec36d67fc29cb6e73150d0de27
  edge:
    backend:
      max_dial_attempts_per_peer_per_message: 1
      replication_factor: 1
cryptarchia:
  service:
    bootstrap:
      prolonged_bootstrap_period: '1.000000000'
      force_bootstrap: false
      offline_grace_period:
        grace_period: '1200.000000000'
        state_recording_interval: '60.000000000'
  network:
    bootstrap:
      ibd:
        peers: []
        delay_before_new_download:
          secs: 10
          nanos: 0
    sync:
      orphan:
        max_orphan_cache_size: 1000
    network:
      max_connected_peers_to_try_download: 16
      max_discovered_peers_to_try_download: 16
  leader:
    wallet:
      max_tx_fee: 18446744073709551615
      funding_pk: f109953967d35247e1b730defe9e8f8ee572f24eceb6b22704eeac8560f62f0c
time:
  backend:
    server: pool.ntp.org:123
    client:
      timeout: '5.000000000'
      listening_interface: 0.0.0.0
    update_interval: '16.000000000'
sdp:
  declaration_id: 5d12efd6e34d3a2cb6772a1da3d4f29ff9a49b40cdff0200c46b32044b5663c5
  wallet:
    max_tx_fee: 18446744073709551615
    funding_pk: f109953967d35247e1b730defe9e8f8ee572f24eceb6b22704eeac8560f62f0c
api:
  backend:
    listen_address: 0.0.0.0:18080
    cors_origins: []
    timeout: 30
    max_body_size: 10485760
    max_concurrent_requests: 1000
  testing:
    listen_address: 127.0.0.1:20003
    cors_origins: []
    timeout: 30
    max_body_size: 10485760
    max_concurrent_requests: 1000
storage:
  backend:
    folder_name: ./db
    read_only: false
    column_family: blocks
kms:
  backend:
    keys:
      f109953967d35247e1b730defe9e8f8ee572f24eceb6b22704eeac8560f62f0c: !Zk 7364707f832b3b8fee49adc02c09c12000000000000000000000000000000000
      34e24f719961d9da080e4d4ef6bf59020ac4deb9ed397b80f07dc4a09459f028: !Zk 626e7f832b3b8fee49adc02c09c1208500000000000000000000000000000000
      a530cc60636fb43a23f11f40fd4b73724f6bb6ec36d67fc29cb6e73150d0de27: !Zk 5543e40a351cef4e2214fbed5d69a3f73cd94e9181db021855c37eb3eb1dc806
      d731e00126f55e9ecfb1d1bd47e599c2728e347f4a865449e133db5486233916: !Zk e5514f45766d105c161f2f8ad0f94e5bd12642b57c76d259df55fb77ac2fa50e
      0e0cde7d44bba40dbcc206acc7a6d5ae9c4ba0e4ace02110902294f94b774909: !Zk 6c647f832b3b8fee49adc02c09c1208500000000000000000000000000000000
      5843e4daf0fc941ad665275b37223f7054e2d215a5acf340d2a313574409f597: !Ed25519 7f832b3b8fee49adc02c09c12085d81555739a1a64b7a438654cf32c5ad14725
wallet:
  known_keys:
    0e0cde7d44bba40dbcc206acc7a6d5ae9c4ba0e4ace02110902294f94b774909: 0e0cde7d44bba40dbcc206acc7a6d5ae9c4ba0e4ace02110902294f94b774909
    d731e00126f55e9ecfb1d1bd47e599c2728e347f4a865449e133db5486233916: d731e00126f55e9ecfb1d1bd47e599c2728e347f4a865449e133db5486233916
    f109953967d35247e1b730defe9e8f8ee572f24eceb6b22704eeac8560f62f0c: f109953967d35247e1b730defe9e8f8ee572f24eceb6b22704eeac8560f62f0c
  voucher_master_key_id: 0e0cde7d44bba40dbcc206acc7a6d5ae9c4ba0e4ace02110902294f94b774909
tracing:
  logger:
    file:
      directory: ./state/logs
      prefix: null
    loki: null
    gelf: null
    otlp:
      endpoint: http://otel:4317/
      service_name: node-genesis-3.nomos-genesis
    stdout: true
    stderr: false
  tracing: None
  filter: None
  metrics: !Otlp
    endpoint: "http://otel-opentelemetry-collector.opentelemetry:4317/"
    host_identifier: "node-genesis-3"
  console: None
  level: DEBUG
state:
  base_folder: ./state
