apiVersion: v1
kind: Pod
metadata:
  name: publisher
  namespace: zerotesting
  labels:
    app: zerotenkay
spec:
  dnsConfig:
    searches:
      - zerotesting-service.zerotesting.svc.cluster.local
  containers:
    - name: publisher-container
      image: soutullostatus/publisher:v0.4.0
      imagePullPolicy: Always
      command:
        - sh
        - -c
        - python /app/traffic.py --messages=2400  --msg-size-kbytes=1 --delay-seconds=1 --pubsub-topic="/waku/2/default-waku/proto" --debug
