apiVersion: v1
kind: Pod
metadata:
  name: publisher
  namespace: rln-test
spec:
  restartPolicy: Never
  dnsConfig:
    searches:
      - zerotesting-service.rln-test.svc.cluster.local
  containers:
    - name: publisher-container
      image: soutullostatus/publisher:testing
      imagePullPolicy: Always
      command:
        - sh
        - -c
        - |
          python /app/traffic.py \
          --messages=1 \
          --msg-size-kbytes=1 \
          --delay-seconds=1 \
          --pubsub-topic="/waku/2/rs/66/" \
          --protocols relay
