apiVersion: v1
kind: Pod
metadata:
  name: publisher
  namespace: rln-test
spec:
  restartPolicy: Never
  containers:
    - name: publisher-container
      image: soutullostatus/publisher:v1.0.4
      imagePullPolicy: Always
      command:
        - sh
        - -c
        - |
          python /app/traffic.py \
          --messages=5 \
          --msg-size-kbytes=1 \
          --delay-seconds=1 \
          --pubsub-topic="/waku/2/rs/66/" \
          --protocols relay \
          --service-names rln-nodes \
          --log-level debug