name: CI

on:
  push:
    branches: [pwhite/test_ci]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  lint:
    name: Lint (autoflake, isort, black)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6

      - run: uv sync --frozen

      - name: black version
        run: uv run black --version
      - name: python version
        run: uv run python --version

      - name: Check unused imports (autoflake)
        run: uv run autoflake --remove-all-unused-imports --recursive --check .

      - name: Check import order (isort)
        run: uv run isort --profile black -l 100 --check-only --diff .

      - name: Check formatting (black)
        run: uv run black -l 100 --check --diff .
