# Topology Configuration File

# Available topology types: random, scale_free, small_world
topology_type: "random"

# Parameters for topology generation
parameters:
  # For random (Erdős-Rényi) topology:
  n: 10  # number of nodes
  p: 0.2  # probability of edge creation

  # For scale-free (Barabási-Albert) topology:
  # n: 10  # number of nodes
  # m: 2   # number of edges to attach from a new node

  # For small-world (Watts-Strogatz) topology:
  # n: 10  # number of nodes
  # k: 4   # each node is connected to k nearest neighbors
  # p: 0.1 # probability of rewiring each edge 